### ISSUE TITLE
How to test examples

### ISSUE THREAD

**Issue by thechordmaster** [RobTillaart/AD5620#7]
Could you help me out on how to test this in terms of wiring to check if the included sawtooth wave example works?

**Comment by RobTillaart** [comment]
You need to connect the device to the Arduino.
Make notes of the Portenta pins you connect the AD5620 pins to. 
You should adjust these pins in the code.

The sawtooth should appear on the Vout

![image](https://github.com/user-attachments/assets/bdb5e0ad-ea00-4683-bb37-cfd9239b287d)


![image](https://github.com/user-attachments/assets/b8b64d0b-69b4-48c6-99ca-a42ddc60abb7)

**Comment by RobTillaart** [comment]
Assuming the question has been answered I close this issue.
Feel free to reopen if same problem exists.
