### ISSUE TITLE
Testing the examples with a UNO

### ISSUE THREAD

**Issue by thechordmaster** [RobTillaart/AD5620#8]
I tried running the example code(sawtooth) wired the setup as below:

5620  - UNO
CLK   - SCK (ICSP HEADER PIN)
DIN   - MOSI (ICSP HEADER PIN)
SYNC - PIN 8 OF THE UNO (As per the line in the example AD5620 AD16_HW(8, &SPI);)
Vdd - 3v3 pin
GND - GND

Tried measuring with an oscilloscope at Vout and GND - only get an erratic waveform that does not correlate with the frequency specified in code. Am I doing something wrong?
Should I be editing the AD5620 AD16_SW(5, 6, 7); line?

**Comment by RobTillaart** [comment]
Do you know the difference between software SPI and hardware SPI?

If you have a scope you should be able to determine the SPI pins used.

1. Disconnect the device
2. Start the sawtooth example
3. check all pins to see where the clock signal is (train of 8 pulses)
4. check all pins to see where the data pins is  (variable set of pulses)

**Comment by RobTillaart** [comment]
Stripped version that uses the software SPI pins (5 = CS, 6 = DATA, 7 = CLOCK).

You should see the pulses of the three lines on the scope.
If not there is a problem with your board.

```cpp
//
//    FILE: AD5620_sawtooth.ino
//  AUTHOR: Rob Tillaart
// PURPOSE: test basic behaviour and performance
//     URL: https://github.com/RobTillaart/AD5620

#include "AD5620.h"

AD5620 AD16_SW(5, 6, 7);

float frequency = 50;
float amplitude = 4095;  //  12 bits

void setup()
{
  Serial.begin(115200);
  Serial.println();
  Serial.println(__FILE__);
  Serial.print("AD5620_LIB_VERSION: ");
  Serial.println(AD5620_LIB_VERSION);

  AD16_SW.begin();
  
  Serial.print("HWSPI: ");
  Serial.println(AD16_SW.usesHWSPI());
}

void loop()
{
  float period = 1000000.0 / frequency;
  float value = fmod(millis(), period);   //  0..period
  //  value = period - value;  //  reverse

  value = amplitude * value / period;
  AD16_SW.setValue(value);
  Serial.println(value);
  delay(1);
}

//  -- END OF FILE --
```

**Comment by RobTillaart** [comment]
With this sketch you should be able to see signals on
- HW SPI pins 8 (SYNC) ,11 (MISO) ,13 (CLOCK) 
- SW SPI pins 5 (SYNC), 6 (MISO), 7 (CLOCK)

**Comment by RobTillaart** [comment]
something like 
![ad5620 clock](https://github.com/user-attachments/assets/c2c43092-7305-4e4f-ba86-bdc3ae3e7a08)

**Comment by RobTillaart** [comment]
data something like
![ad5620 data](https://github.com/user-attachments/assets/ca017d02-02c6-4750-bc8f-75b6f672083a)

**Comment by RobTillaart** [comment]
Between the two data bytes there is a very small moment HIGH (in the middle).

**Comment by RobTillaart** [comment]
Think I found a bug in the library

from datasheet
_In a normal write sequence for the AD5660, the SYNC line is kept low for at least 24 falling edges of SCLK, and the DAC is updated on the 24th falling edge. However, if SYNC is brought high before the 24th falling edge, this acts as an interrupt to the write sequence._

As there are only 2 data bytes to send I bring the sync high after the 16th bit so the device is reset.
So I will create a develop branch which sends three bytes asap.

**Comment by RobTillaart** [comment]
24 bits clocks out perfectly (no pull ups cause jitter)

![ad5620 data clock](https://github.com/user-attachments/assets/bc4d0a1a-e86a-4f37-94c5-35d8b8a62f27)

**Comment by RobTillaart** [comment]
@thechordmaster 

Please give the develop branch a try.

**Comment by RobTillaart** [comment]
Root cause is building code on the picture, which shows 16 bit for the AD5620 and AD5640.

![image](https://github.com/user-attachments/assets/6e8a62a5-d3b7-40d1-93d4-fa9351b68681)

**Comment by RobTillaart** [comment]
@thechordmaster 
I have merged the develop branch, and if it doesn't work just open a new issue.

Thanks,
